### PR TITLE
chore: add auto-label to requestor service

### PR DESCRIPTION
**Pull request by atharvar28**
Adding auto-label feature to the repo

### CODE REVIEW

**Review by themarcelor — APPROVED** [review]
+1

**Comment by paulineribeyre** [comment]
@atharvar28 @themarcelor instead why don't we configure the tests to run for repos data-portal and requestor (in gen3-qa), like we do for other features? 🤔

**Comment by themarcelor** [comment]
@paulineribeyre , I think the labelling give us an explicit interface so we know exactly what is running.
But we should definitely revisit this testing strategy for StudyViewer in a future iteration (including enabling the test on all CI environments using a new studyViewer config knowledge that arose recently).

**Review by themarcelor — APPROVED** [review]
+1

**Pull request merged**
